create database SCM_etl

 create schema SCM_etl.SCM_schema

use schema SCM_etl.SCM_schema


SELECT * FROM RAW_SUPPLY_CHAIN LIMIT 5;

--Total Quantity Shipped Per Product Category
SELECT 
    CATEGORY_NAME,
    SUM(ORDER_ITEM_QUANTITY) AS TOTAL_QUANTITY_SHIPPED
FROM RAW_SUPPLY_CHAIN
GROUP BY CATEGORY_NAME
ORDER BY TOTAL_QUANTITY_SHIPPED DESC;


----Most Efficient Warehouses by Average Shipping Time

SELECT 
    SHIPPING_MODE,
    ROUND(AVG(DAYS_FOR_SHIPPING_REAL), 2)        AS AVG_ACTUAL_DAYS,
    ROUND(AVG(DAYS_FOR_SHIPMENT_SCHEDULED), 2)   AS AVG_SCHEDULED_DAYS,
    ROUND(AVG(DAYS_FOR_SHIPMENT_SCHEDULED 
              - DAYS_FOR_SHIPPING_REAL), 2)       AS EFFICIENCY_SCORE,
    COUNT(*)                                      AS TOTAL_SHIPMENTS
FROM RAW_SUPPLY_CHAIN
GROUP BY SHIPPING_MODE
ORDER BY EFFICIENCY_SCORE DESC;


----Total Shipment Value Per Supplier

SELECT 
    DEPARTMENT_NAME,
    COUNT(*)                                    AS TOTAL_ORDERS,
    SUM(ORDER_ITEM_QUANTITY)                    AS TOTAL_QUANTITY,
    ROUND(SUM(SALES), 2)                        AS TOTAL_SALES_VALUE,
    ROUND(SUM(ORDER_PROFIT_PER_ORDER), 2)       AS TOTAL_PROFIT,
    ROUND(AVG(SALES), 2)                        AS AVG_ORDER_VALUE
FROM RAW_SUPPLY_CHAIN
GROUP BY DEPARTMENT_NAME
ORDER BY TOTAL_SALES_VALUE DESC;

----Top 5 Products by Highest Shipment Quantity

SELECT 
    PRODUCT_NAME,
    CATEGORY_NAME,
    SUM(ORDER_ITEM_QUANTITY)        AS TOTAL_QUANTITY_SHIPPED,
    COUNT(*)                        AS TOTAL_ORDERS,
    ROUND(SUM(SALES), 2)            AS TOTAL_REVENUE
FROM RAW_SUPPLY_CHAIN
GROUP BY PRODUCT_NAME, CATEGORY_NAME
ORDER BY TOTAL_QUANTITY_SHIPPED DESC
LIMIT 5;




-----------Distribution of Shipment Values Per Product Category

SELECT 
    CATEGORY_NAME,
    COUNT(*)                                AS TOTAL_ORDERS,
    ROUND(SUM(SALES), 2)                    AS TOTAL_VALUE,
    ROUND(AVG(SALES), 2)                    AS AVG_ORDER_VALUE,
    ROUND(MIN(SALES), 2)                    AS MIN_ORDER_VALUE,
    ROUND(MAX(SALES), 2)                    AS MAX_ORDER_VALUE,
    ROUND(STDDEV(SALES), 2)                 AS VALUE_SPREAD,
    ROUND(SUM(SALES) * 100.0 / 
          SUM(SUM(SALES)) OVER (), 2)       AS PERCENTAGE_OF_TOTAL
FROM RAW_SUPPLY_CHAIN
GROUP BY CATEGORY_NAME
ORDER BY TOTAL_VALUE DESC;



----------STORED PROCEDURE ---> UPDATE SHIPMENT STATUS
CREATE OR REPLACE PROCEDURE UPDATE_SHIPMENT(
    P_ORDER_ID     NUMBER,
    P_DELAY_DAYS   NUMBER,
    P_NEW_STATUS   VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    UPDATE RAW_SUPPLY_CHAIN
    SET 
        DAYS_FOR_SHIPPING_REAL = DAYS_FOR_SHIPPING_REAL + :P_DELAY_DAYS,
        ORDER_STATUS           = :P_NEW_STATUS
    WHERE ORDER_ID = :P_ORDER_ID;
    
    RETURN 'SUCCESS: Order updated!';
END;
$$;

CALL UPDATE_SHIPMENT(75936, 3, 'DELAYED');
SELECT ORDER_ID, DAYS_FOR_SHIPPING_REAL, ORDER_STATUS
FROM RAW_SUPPLY_CHAIN
WHERE ORDER_ID = 75936;


------------view of shipment performance
CREATE OR REPLACE VIEW SHIPMENT_PERFORMANCE_VIEW AS
SELECT 
    CATEGORY_NAME,
    SHIPPING_MODE,
    COUNT(*)                                   AS TOTAL_ORDERS,
    SUM(ORDER_ITEM_QUANTITY)                   AS TOTAL_QUANTITY,
    ROUND(SUM(SALES), 2)                       AS TOTAL_REVENUE,
    ROUND(AVG(DAYS_FOR_SHIPPING_REAL), 2)      AS AVG_SHIPPING_DAYS,
    ROUND(AVG(DAYS_FOR_SHIPMENT_SCHEDULED), 2) AS AVG_SCHEDULED_DAYS
FROM RAW_SUPPLY_CHAIN
GROUP BY CATEGORY_NAME, SHIPPING_MODE
ORDER BY TOTAL_REVENUE DESC;


SELECT * FROM SHIPMENT_PERFORMANCE_VIEW;


-----------------------
WITH YEARLY_SALES AS (
    SELECT 
        DEPARTMENT_NAME,
        YEAR(TRY_TO_DATE(ORDER_DATE_DATEORDERS, 'MM/DD/YYYY HH24:MI')) AS SALE_YEAR,
        ROUND(SUM(SALES), 2)             AS TOTAL_SALES
    FROM RAW_SUPPLY_CHAIN
    GROUP BY DEPARTMENT_NAME, YEAR(TRY_TO_DATE(ORDER_DATE_DATEORDERS, 'MM/DD/YYYY HH24:MI'))
)
SELECT 
    CURRENT_YEAR.DEPARTMENT_NAME,
    CURRENT_YEAR.SALE_YEAR,
    CURRENT_YEAR.TOTAL_SALES            AS THIS_YEAR_SALES,
    LAST_YEAR.TOTAL_SALES               AS LAST_YEAR_SALES,
    ROUND(CURRENT_YEAR.TOTAL_SALES 
        - LAST_YEAR.TOTAL_SALES, 2)     AS DIFFERENCE,
    ROUND((CURRENT_YEAR.TOTAL_SALES 
        - LAST_YEAR.TOTAL_SALES) * 100.0 
        / LAST_YEAR.TOTAL_SALES, 2)     AS CHANGE_PERCENTAGE
FROM YEARLY_SALES CURRENT_YEAR
JOIN YEARLY_SALES LAST_YEAR
    ON  CURRENT_YEAR.DEPARTMENT_NAME = LAST_YEAR.DEPARTMENT_NAME
    AND CURRENT_YEAR.SALE_YEAR       = LAST_YEAR.SALE_YEAR + 1
ORDER BY CHANGE_PERCENTAGE DESC;

---------------------history tracking trigger
CREATE OR REPLACE TABLE SHIPMENT_HISTORY (
    HISTORY_ID        NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_ID          NUMBER,
    CHANGED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CHANGE_TYPE       VARCHAR(10),
    OLD_ORDER_STATUS  VARCHAR(50),
    OLD_SHIPPING_DAYS NUMBER,
    OLD_SALES         FLOAT
);

---------stream
CREATE OR REPLACE STREAM SHIPMENT_STREAM
ON TABLE RAW_SUPPLY_CHAIN;


------------task
CREATE OR REPLACE TASK SHIPMENT_HISTORY_TASK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE  = '1 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA('SHIPMENT_STREAM')
AS
    INSERT INTO SHIPMENT_HISTORY (
        ORDER_ID,
        CHANGE_TYPE,
        OLD_ORDER_STATUS,
        OLD_SHIPPING_DAYS,
        OLD_SALES
    )
    SELECT 
        ORDER_ID,
        CASE 
            WHEN METADATA$ACTION = 'DELETE' THEN 'DELETE'
            ELSE 'UPDATE'
        END,
        ORDER_STATUS,
        DAYS_FOR_SHIPPING_REAL,
        SALES
    FROM SHIPMENT_STREAM
    WHERE METADATA$ACTION = 'DELETE';

    ALTER TASK SHIPMENT_HISTORY_TASK RESUME;
    CALL UPDATE_SHIPMENT(75936, 2, 'LATE');


    SELECT * FROM SHIPMENT_HISTORY;
    =-----checking

SELECT ORDER_ID, ORDER_STATUS, DAYS_FOR_SHIPPING_REAL
FROM RAW_SUPPLY_CHAIN
WHERE ORDER_ID = 75936;

CALL UPDATE_SHIPMENT(75936, 2, 'LATE');

SELECT * FROM SHIPMENT_STREAM;

EXECUTE TASK SHIPMENT_HISTORY_TASK;

SELECT * FROM SHIPMENT_HISTORY